### ISSUE TITLE
Can't download the Sense action recognition model

### ISSUE THREAD

**Issue by davideferrari95** [alberttjc/hiROS#2]
Hi, 

Following the installation procedure, when downloading the Sense Pre-Trained Weights I get the following error, trying to access the 20bn website:

_503 Service Temporarily Unavailable_

Where I can download those files ?
I can use some other datasets ?

Best Regards,
Davide

**Comment by alberttjc** [comment]
Hi @davideferrari95,

Thank you for raising this issue, I will need to contact the original repo owners and enquire about the current status of the project/training files. As a researcher, I cannot distribute these files without their consent/approval. I will attempt to contact them and update you when I hear back from them. You are welcome to contact them yourself :)

Regarding your second inquiry, you can utilize a different dataset that you find, however, I personally have not done so. From experience, you will need a very large dataset to create a model that has reasonable accuracy. 

Regards,
Albert

**Comment by alberttjc** [comment]
Looks like it may be a common issue, this may take longer than expected :(

https://github.com/quic/sense/issues/184

**Comment by davideferrari95** [comment]
Thank you very much for the quick reply.

In their GitHub repository there are already some open issues regarding this problem but with no answers. I couldn't find any other way to contact the developers of the original repository directly, so I posted here hoping to get a different solutions. I await some good news.

In the meantime I can try to download the something-something v2 or the jester datasets.

**Comment by alberttjc** [comment]
I have briefly gone through the something-something v2 project and it implements similar concepts, I wish you the best of luck!

The blogpost from the root repo is pretty useful: 
https://medium.com/twentybn/towards-situated-visual-ai-via-end-to-end-learning-on-video-clips-2832bd9d519f 

Hopefully I hear back from some of the developers :)

**Comment by davideferrari95** [comment]
I have been looking for a solution for days but none of the databases are accessible as they are all owners of Twenty Billion Neurons which was purchased by Qualcomm.

As a result, the something-something v2 and jester databases are currently inaccessible and no one seems to be responding to multiple access requests from the community. 

What possible alternatives can I use to implement this work ?

**Comment by slowlyC** [comment]
Have you got the model or other method？

**Comment by alberttjc** [comment]
Hi @ds862, unfortunately, I have yet to hear back from them! 

@davideferrari95 may I ask what are you planning to do? maybe I can give some ideas :)

**Comment by davideferrari95** [comment]
> Hi @ds862, unfortunately, I have yet to hear back from them!
> 
> @davideferrari95 may I ask what are you planning to do? maybe I can give some ideas :)

Hi, I tried to contact Qualcomm support to get access to the pre-trained weights. I am currently awaiting a response.

**Comment by MoonBunnyZZZ** [comment]
> > Hi @ds862, unfortunately, I have yet to hear back from them!
> > @davideferrari95 may I ask what are you planning to do? maybe I can give some ideas :)
> 
> Hi, I tried to contact Qualcomm support to get access to the pre-trained weights. I am currently awaiting a response.

Hi, do you get response?

**Comment by alberttjc** [comment]
@MoonBunnyZZZ Unfortunately I did not get a response

**Comment by lindychan** [comment]
> 嗨@davideferrari95，
> 
> 感谢您提出这个问题，我需要联系原始 repo 所有者并询问项目/培训文件的当前状态。作为一名研究人员，未经他们的同意/批准，我不能分发这些文件。当我收到他们的回复时，我会尝试与他们联系并更新您。欢迎您自己联系他们:)
> 
> 关于您的第二个查询，您可以使用您找到的不同数据集，但是，我个人还没有这样做。根据经验，您将需要一个非常大的数据集来创建具有合理精度的模型。
> 
> 问候， 阿尔伯特

`./ python examples/run_gesture_control.py
Could not find at least one of the following files:
{
    "backbone": "backbone/strided_inflated_efficientnet.ckpt",
    "gesture_control": "gesture_control/sien_last_9_layers.ckpt"
}
Could not find at least one of the following files:
{
    "backbone": "backbone/strided_inflated_efficientnet_lite.ckpt",
    "gesture_control": "gesture_control/sien_lite_last_9_layers.ckpt"
}
ERROR - Weights files missing. To download, please go to https://20bn.com/licensing/sdk/evaluation andfollow the instructions.
Traceback (most recent call last):
  File "examples/run_gesture_control.py", line 142, in <module>
    use_gpu=args['--use_gpu'],
  File "examples/run_gesture_control.py", line 72, in run_gesture_control
    model_version
  File "/usr/local/chenlin_space/sense/sense/loading.py", line 150, in get_relevant_weights
    raise Exception(msg)
Exception: ERROR - Weights files missing. To download, please go to https://20bn.com/licensing/sdk/evaluation andfollow the instructions.
root@1bb1de11f031:/usr/local/chenlin_space/sense# PYTHONPATH=./ python examples/run_gesture_control.py
Traceback (most recent call last):
  File "examples/run_gesture_control.py", line 42, in <module>
    from sense.loading import get_relevant_weights
  File "/usr/local/chenlin_space/sense/sense/loading.py", line 18, in <module>
    MODELS['StridedInflatedEfficientNet']['pro']['backbone'],
KeyError: 'backbone'`

could you help me ?

**Comment by davideferrari95** [comment]
> > 嗨@davideferrari95，
> 
> > 
> 
> > 感谢您提出这个问题，我需要联系原始 repo 所有者并询问项目/培训文件的当前状态。作为一名研究人员，未经他们的同意/批准，我不能分发这些文件。当我收到他们的回复时，我会尝试与他们联系并更新您。欢迎您自己联系他们:)
> 
> > 
> 
> > 关于您的第二个查询，您可以使用您找到的不同数据集，但是，我个人还没有这样做。根据经验，您将需要一个非常大的数据集来创建具有合理精度的模型。
> 
> > 
> 
> > 问候， 阿尔伯特
> 
> 
> 
> `./ python examples/run_gesture_control.py
> 
> Could not find at least one of the following files:
> 
> {
> 
>     "backbone": "backbone/strided_inflated_efficientnet.ckpt",
> 
>     "gesture_control": "gesture_control/sien_last_9_layers.ckpt"
> 
> }
> 
> Could not find at least one of the following files:
> 
> {
> 
>     "backbone": "backbone/strided_inflated_efficientnet_lite.ckpt",
> 
>     "gesture_control": "gesture_control/sien_lite_last_9_layers.ckpt"
> 
> }
> 
> ERROR - Weights files missing. To download, please go to https://20bn.com/licensing/sdk/evaluation andfollow the instructions.
> 
> Traceback (most recent call last):
> 
>   File "examples/run_gesture_control.py", line 142, in <module>
> 
>     use_gpu=args['--use_gpu'],
> 
>   File "examples/run_gesture_control.py", line 72, in run_gesture_control
> 
>     model_version
> 
>   File "/usr/local/chenlin_space/sense/sense/loading.py", line 150, in get_relevant_weights
> 
>     raise Exception(msg)
> 
> Exception: ERROR - Weights files missing. To download, please go to https://20bn.com/licensing/sdk/evaluation andfollow the instructions.
> 
> root@1bb1de11f031:/usr/local/chenlin_space/sense# PYTHONPATH=./ python examples/run_gesture_control.py
> 
> Traceback (most recent call last):
> 
>   File "examples/run_gesture_control.py", line 42, in <module>
> 
>     from sense.loading import get_relevant_weights
> 
>   File "/usr/local/chenlin_space/sense/sense/loading.py", line 18, in <module>
> 
>     MODELS['StridedInflatedEfficientNet']['pro']['backbone'],
> 
> KeyError: 'backbone'`
> 
> 
> 
> could you help me ?

Sorry but I don't understand Chinese... From your log error seems you missed the pre-trained models we are asking for.
Actually Qualcomm doesn't reply and the official repo seems dead. I tried to mail a lot of address but without response so I moved to other libraries in order to reply this functionality. 
If someone can share that models we solve the problem.

**Comment by davideferrari95** [comment]
Hi @alberttjc, 

I found on he Qualcomm website the Jester dataset [download section](https://developer.qualcomm.com/software/ai-datasets/jester).  Is it sometching we can use to solve this problem ? How ?
